<?php

namespace Blogger\BlogBundle\Repository;

use Doctrine\ORM\EntityManager;
use \Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{

    public function __construct(EntityManager $entityManager, Mapping\ClassMetadata $class)
    {
        parent::__construct($entityManager, $class);
    }

    public function getLatest(int $limit, int $offset)
    {

    }

}
