#blogger_blog_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: BloggerBlogBundle:Default:index, name: world}

# src/Blogger/BlogBundle/Resources/config/routing.yml

index:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }

blogger_about:
    path: /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    methods: [GET]

blog_view:
    path:     /view/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:view }
    methods: [GET]
    requirements:
        id: \d+

blog_create:
    path:     /create
    defaults: { _controller: BloggerBlogBundle:Blog:create }
    methods: [GET, POST]

blog_edit:
    path:     /edit/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:edit }
    methods: [GET, POST]
    requirements:
        id: \d+

blog_delete:
    path:     /delete/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:delete }
    methods: [GET, DELETE]
    requirements:
        id: \d+
